enum EndPoints {
  documentos = '/proyecto/:proyecto_id/documentos',
  excel_export = '/proyecto/:proyecto_id/export-excel',
  import_excel = '/import-excel',
  entidad = '/proyecto/:proyecto_id/entidad',
  rol = '/rol',
  financiador = '/financiador',
  socio_local = '/socio_local',
  agente = '/agente',
  convocatoria = '/convocatoria',
  implementador = '/implementador',
  etapa = '/proyecto/:proyecto_id/etapa',
  pago = '/proyecto/:proyecto_id/gasto/:gasto_id/pago',
  informe = '/proyecto/:proyecto_id/informe',
  periodo = '/proyecto/:proyecto_id/periodo',
  aportacion = '/proyecto/:proyecto_id/aportacion',
  modificacion = '/proyecto/:proyecto_id/modificacion',
  cuenta_bancaria = '/proyecto/:proyecto_id/cuenta_bancaria',
  partida = '/proyecto/:proyecto_id/partida',
  presupuesto = '/proyecto/:proyecto_id/presupuesto',
  gasto = '/proyecto/:proyecto_id/gasto',
  gasto_documento = '/proyecto/:proyecto_id/gasto/:gasto_id/documentos_files',
  gasto_documento_download = '/proyecto/:proyecto_id/gasto/:gasto_id/documentos_files/download',
  objetivo_general = '/proyecto/:proyecto_id/objetivo',
  objetivo_especifico = '/proyecto/:proyecto_id/objetivo_especifico',
  indicador_og = '/proyecto/:proyecto_id/objetivo/:objetivo_id/indicador',
  indicador_oe = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador',
  fuente_vrificacion_og = '/proyecto/:proyecto_id/objetivo/:objetivo_id/indicador/:indicador_id/fuentes_verificacion',
  medida_og = '/proyecto/:proyecto_id/objetivo/:objetivo_id/indicador/:indicador_id/medida',
  fuente_vrificacion_oe = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador/:indicador_id/fuentes_verificacion',
  medida_oe = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador/:indicador_id/medida',
  hip_objetivo_especifico = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/hipotesis',
  categoria = '/categoria',
  proyecto = '/proyecto',
  proyecto_gong = '/gong',
  pais = '/pais',
  moneda = '/moneda',
  localizacion = '/localizacion',
  cofinanciador = '/cofinanciador',
  contrato = '/contrato',
  tipo_periodo = '/tipo_periodo',
  tipo_valoracion = '/tipo_valoracion',
  tipo_movimiento = '/tipo_movimiento',
  tipo_partida = '/tipo_partida',
  tipo_personal = '/tipo_personal',
  estados_informe = '/estados_informe',
  estados_proyecto = '/estados_proyecto',
  actividad_global = '/proyecto/:proyecto_id/actividad_global',
  actividad_global_recurso = '/proyecto/:proyecto_id/actividad_global/:actividad_global_id/recurso',
  resultado = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado',
  resultado_hipotesis = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/hipotesis',
  resultado_indicador = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador',
  // tslint:disable-next-line:max-line-length
  resultado_fuente_verificacion = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador/:indicador_id/fuentes_verificacion',
  resultado_medida = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador/:indicador_id/medida',
  resultado_actividad = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/actividades',
  actividad_recurso = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/actividad/:actividad_id/recursos',
  usuario = '/users',
  empresa = '/empresa',
  costes = '/costes',
  persona = '/proyecto/:proyecto_id/persona',
  bien = '/proyecto/:proyecto_id/bien',
  operacion_bancaria = '/proyecto/:proyecto_id/operacion_bancaria',
  validacion = '/proyecto/:proyecto_id/validacion',
  validacion_catalogo = '/proyecto/:proyecto_id/validacion_catalogos',
  validacion_proyecto = '/proyecto/:proyecto_id/validacion_proyectos',
  og_fuente_verificacion_documento =
  '/proyecto/:proyecto_id/objetivo/:objetivo_id/indicador/:indicador_id/fuentes_verificacion/:fuente_verificacion_id/documentos_files',
  og_fuente_verificacion_documento_download =
  '/proyecto/:proyecto_id/objetivo/:objetivo_id/indicador/:indicador_id/fuentes_verificacion/:fuente_verificacion_id/documentos_files/download',
  oe_fuente_verificacion_documento =
  '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador/:indicador_id/fuentes_verificacion/:fuente_verificacion_id/documentos_files',
  oe_fuente_verificacion_documento_download =
  // tslint:disable-next-line:max-line-length
  '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador/:indicador_id/fuentes_verificacion/:fuente_verificacion_id/documentos_files/download',
  resultado_fuente_verificacion_documento =
  // tslint:disable-next-line:max-line-length
  '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador/:indicador_id/fuentes_verificacion/:fuente_verificacion_id/documentos_files',
  resultado_fuente_verificacion_documento_download =
  // tslint:disable-next-line:max-line-length
  '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador/:indicador_id/fuentes_verificacion/:fuente_verificacion_id/documentos_files/download',
  oe_comentarios = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/comentarios',
  resultado_comentarios = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/comentarios',
  resultado_ind_comentarios = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador/:indicador_id/comentarios',
  resultado_act_comentarios = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/actividad/:actividad_id/comentarios',
  // og_indicador_medidas = '',
  oe_indicador_medidas = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador/:indicador_id/medida',
  oe_ind_comentarios = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/indicador/:indicador_id/comentarios',
  og_ind_comentarios = '/proyecto/:proyecto_id/objetivo/:objetivo_id/indicador/:indicador_id/comentarios',
  resultado_indicador_medidas = '/proyecto/:proyecto_id/objetivo_especifico/:objetivo_especifico_id/resultado/:resultado_id/indicador/:indicador_id/medida',
}
export { EndPoints };

